export const TIMEZONES = [
  { label: 'Eastern Time (New York)', value: 'America/New_York' },
  { label: 'Central Time (Chicago)', value: 'America/Chicago' },
  { label: 'Mountain Time (Denver)', value: 'America/Denver' },
  { label: 'Pacific Time (Los Angeles)', value: 'America/Los_Angeles' },
  { label: 'Alaska Time (Anchorage)', value: 'America/Anchorage' },
  { label: 'Hawaii Time (Honolulu)', value: 'Pacific/Honolulu' },
  { label: 'Mountain Standard Time (Phoenix)', value: 'America/Phoenix' },
  { label: 'Eastern Time (Toronto)', value: 'America/Toronto' },
  { label: 'Pacific Time (Vancouver)', value: 'America/Vancouver' },
  { label: 'Atlantic Time (Halifax)', value: 'America/Halifax' },
  { label: 'Mexico City Time', value: 'America/Mexico_City' },
  { label: 'Central America Time (Guatemala)', value: 'America/Guatemala' },
  { label: 'Colombia Time (Bogota)', value: 'America/Bogota' },
  { label: 'Peru Time (Lima)', value: 'America/Lima' },
  { label: 'Chile Time (Santiago)', value: 'America/Santiago' },
  { label: 'Argentina Time (Buenos Aires)', value: 'America/Buenos_Aires' },
  { label: 'Brazil Time (São Paulo)', value: 'America/Sao_Paulo' },
  { label: 'Venezuela Time (Caracas)', value: 'America/Caracas' },
  { label: 'London (GMT/BST)', value: 'Europe/London' },
  { label: 'Dublin Time (IST/GMT)', value: 'Europe/Dublin' },
  { label: 'Paris (CET/CEST)', value: 'Europe/Paris' },
  { label: 'Berlin (CET/CEST)', value: 'Europe/Berlin' },
  { label: 'Rome (CET/CEST)', value: 'Europe/Rome' },
  { label: 'Madrid (CET/CEST)', value: 'Europe/Madrid' },
  { label: 'Amsterdam (CET/CEST)', value: 'Europe/Amsterdam' },
  { label: 'Athens (EET/EEST)', value: 'Europe/Athens' },
  { label: 'Istanbul (TRT)', value: 'Europe/Istanbul' },
  { label: 'Moscow Time (MSK)', value: 'Europe/Moscow' },
  { label: 'Dubai (Gulf Standard Time)', value: 'Asia/Dubai' },
  { label: 'Riyadh (Arabia Standard Time)', value: 'Asia/Riyadh' },
  { label: 'Tehran (Iran Time)', value: 'Asia/Tehran' },
  { label: 'Jerusalem (Israel Time)', value: 'Asia/Jerusalem' },
  { label: 'Karachi (Pakistan Time)', value: 'Asia/Karachi' },
  { label: 'India Standard Time', value: 'Asia/Kolkata' },
  { label: 'Dhaka (Bangladesh Time)', value: 'Asia/Dhaka' },
  { label: 'Kathmandu (Nepal Time)', value: 'Asia/Kathmandu' },
  { label: 'Bangkok (Indochina Time)', value: 'Asia/Bangkok' },
  { label: 'Singapore Time', value: 'Asia/Singapore' },
  { label: 'Jakarta (Western Indonesia Time)', value: 'Asia/Jakarta' },
  { label: 'Manila (Philippine Time)', value: 'Asia/Manila' },
  { label: 'Kuala Lumpur (Malaysia Time)', value: 'Asia/Kuala_Lumpur' },
  { label: 'Hong Kong Time', value: 'Asia/Hong_Kong' },
  { label: 'Shanghai (China Standard Time)', value: 'Asia/Shanghai' },
  { label: 'Tokyo (JST)', value: 'Asia/Tokyo' },
  { label: 'Seoul (Korea Standard Time)', value: 'Asia/Seoul' },
  { label: 'Sydney (AEDT)', value: 'Australia/Sydney' },
  { label: 'Melbourne (AEDT)', value: 'Australia/Melbourne' },
  { label: 'Brisbane (AEST)', value: 'Australia/Brisbane' },
  { label: 'Perth (AWST)', value: 'Australia/Perth' },
  { label: 'Adelaide (ACDT)', value: 'Australia/Adelaide' },
  { label: 'Auckland (New Zealand)', value: 'Pacific/Auckland' },
  { label: 'Fiji Time', value: 'Pacific/Fiji' },
  { label: 'Cairo (EET)', value: 'Africa/Cairo' },
  { label: 'Johannesburg (SAST)', value: 'Africa/Johannesburg' },
  { label: 'Lagos (West Africa Time)', value: 'Africa/Lagos' },
  { label: 'Nairobi (East Africa Time)', value: 'Africa/Nairobi' },
  { label: 'Casablanca (WET)', value: 'Africa/Casablanca' },
  { label: 'UTC (Coordinated Universal Time)', value: 'UTC' },
];
