const MESSAGES = {
  PROFILE_CREATED: 'Profile created successfully',
  PROFILE_UPDATED: 'Profile updated successfully',
  PROFILE_REQUIRED: 'At least one profile is required',
  PROFILE_NAME_TOO_SMALL: 'Name should be atleast 2 charecters long',
  PROFILE_NOT_FOUND: 'Profile not found',
  PROFILE_NAME_REQUIRED: 'Profile name is required',
  PROFILE_NAME_NOT_VALID: 'Profile name should contain only letters or numbers',
  PROFILE_NAME_EXISTS: 'Profile with this name already exists',
  PROFILES_FETCHED: 'Profiles fetched successfully',
  PROFILES_CHANGED: 'Profiles changed to',
  TIMEZONE_REQUIRED: 'Timezone is required',
  START_TIME_UPDATED: 'Start date/time updated',
  TIME_REQUIRED: 'Start date and end date are required',
  INVALID_DATE: 'Invalid date format',
  END_TIME_UPDATED: 'End date/time updated',
  END_DATE_AFTER_START: 'End date must be after start date',
  START_DATE_CANT_BE_PAST: 'Start date cannot be in the past',
  TIMEZONE_UPDATED: 'Timezone updated',
  EVENT_CREATED: 'Event created successfully',
  EVENT_UPDATED: 'Event updated successfully',
  EVENT_NOT_FOUND: 'Event not found',
  EVENTS_FETCHED: 'Events fetched successfully',
  EVENT_FETCHED: 'Event fetched successfully',
  LOGS_FETCHED: 'Event logs fetched successfully',
};

module.exports = {
  MESSAGES,
};
